### ISSUE TITLE
Target uses selinux but python bindings (libselinux-python) aren't installed!"

### ISSUE THREAD

**Issue by peasead** [rocknsm/rock#103]
Need to add libselinux-python to the Core Packages.

https://github.com/rocknsm/rock/blob/devel/cookbooks/simplerock/recipes/default.rb#L396

**Comment by peasead** [comment]
17f2ab05f6380484ca4ac63e73e763581a2661f1

**Comment by dcode** [comment]
For the `devel` release, please focus on the Ansible sources. The link you posted is for the Chef recipe in 1.0.

**Comment by dcode** [comment]
After discussing in chat, this sounds like it was Ansible erroring out. We might be able to install this package super early in the playbook, or throw it in the wrapper script.

[1] http://docs.ansible.com/ansible/intro_installation.html#managed-node-requirements

**Comment by dcode** [comment]
This actually shouldn't happen w/ ansible, as this package is installed when ansible is installed from RPM.
