### ISSUE TITLE
*Enhancement* For FSF data mappings and functions test we need a super disgusting file that will trigger all the modules

### ISSUE THREAD

**Issue by akniffe1** [rocknsm/rock#107]
This would significantly help in maintaining the FSF component, and would be a worthy thing to drop in the FSF data dir or somewhere else for offline functions tests too. 

@BallsyWalnuts do you have anything that might fit the bill?

**Comment by dcode** [comment]
This was closed by #108 but needs to be purged from the repo since it contains (somewhat safe) live malware
