### ISSUE TITLE
Add to Wiki:  "Change monitored Ethernet port after installation"

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#11]
From Derek:  
How To Update the Ethernet Monitoring Interface AFTER Installation
Modify the following:
1.  /opt/bro/etc/node.cfg
2.  /sbin/ifup-local
3.  The interface script (ifcfg-foo)
4.  The steno config

**Comment by dcode** [comment]
This is actually handled in 2.x by changing the `rock_monifs` item in `/etc/rocknsm/config.yml`. Update that as needed, then re-run `/opt/rocknsm/rock/bin/deploy_rock.sh`.
