### ISSUE TITLE
locate command is not installed 

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#110]
locate command is not installed.  locate is extremely simple to use and it is faster than the find command.

**Comment by peasead** [comment]
Is what you're trying to find, and the frequency of it, worth the indexing resources for `locate`?

Just trying to prioritize.

**Comment by akniffe1** [comment]
@peasead @charlesfair perhaps this could be accommodated with the following updatedb.conf?

Basically we just add /data (where all the sensor outputs get dropped) to the PRUNEPATHS?

This could probably be taken further to also exclude the following--though I'm not sure how impactful it would be. 
* /var/log/elasticsearch
* /var/log/kafka
* /var/log/logstash
* /var/log/zookeeper
* /var/log/suricata
* /var/log/nginx

````
PRUNE_BIND_MOUNTS = "yes"
PRUNEFS = "9p afs anon_inodefs auto autofs bdev binfmt_misc cgroup cifs coda configfs cpuset debugfs devpts ecryptfs exofs fuse fuse.sshfs fusectl gfs gfs2 gpfs hugetlbfs inotifyfs iso9660 jffs2 lustre mqueue ncpfs nfs nfs4 nfsd pipefs proc ramfs rootfs rpc_pipefs securityfs selinuxfs sfs sockfs sysfs tmpfs ubifs udf usbfs"
PRUNENAMES = ".git .hg .svn"
PRUNEPATHS = "/afs /media /mnt /net /sfs /tmp /udev /var/cache/ccache /var/lib/yum/yumdb /var/spool/cups /var/spool/squid /var/tmp /data"
````

**Comment by dcode** [comment]
ROCK is designed as a sensor/collector. `locate` is a user-space tool to help find things. The current ISO as-is tries to include only what is needed for a minimal install. In the future, we will make a more flexible installer ISO that can incorporate other distro groups and environments, custom partition schemes, etc. If you need that sort of functionality right now, the best approach is to install the operating system as you see fit, and use the Ansible scripts to install ROCK on top of it. Alternatively, you can use the online CentOS repositories to install additional packages such as `locate`.

I will keep this issue open to note that we require documentation on specifically how to handle these use-cases.

**Comment by charlesfair** [comment]
ROCK is commonly installed in places where the admin can not access the Internet during the ROCK install process.  This fact is highly supportive of the addition of the locate command.  Also, considering the substantially undocumented nature of ROCK 2.0, the mlocate (locate) command is quite reasonable. Examples, here are basically the same results, but showing that the command "locate" is much simpler:  

"locate":
$ locate config.yml
/etc/rocknsm/config.yml
/etc/rocknsm/config.yml.22814.2017-02-27@06:22:28~
/opt/rocknsm/rock/ansible/templates/rock_config.yml.j2

"find": 
$ find / -name config.yml 2>&1 | grep -v "Permission denied"
/etc/rocknsm/config.yml

**Comment by dcode** [comment]
I get the use-case, but this is not a blocker for 2.0. The core use-case is for a stream-lined, minimal sensor platform.

For now, you can create a custom ISO with additional packages by editing the file `scripts/ks/rock_packages.list` before running the ISO master script. I think the next major upgrade for the installer will allow you to achieve what you're looking for, but I just can't commit to it right now.
