### ISSUE TITLE
USB installation requires Kickstart script location startup parameters mod

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#111]
To successfully install the ROCK 2.0 beta, the startup parameters must be changed.  The default settings point to the Kickstart script residing on the cdrom.  For this to work, the user must hit the tab key and modify the string so the "ks" script location is the same as the drive image.  

* I get the same error if I use EFI or BIOS booting methods 

I successfully used this technique to install ROCK 2.0 on two different systems - same result each time.  I seem to remember when using the iso to install a VM, this is not necessary?!?

**Comment by dcode** [comment]
How did you get this working if you modified the boot line?

**Comment by dcode** [comment]
Ran into an issue where this boots for ISO but not hdd...then I had it working for hdd and not ISO...I think I finally got this worked out.
