### ISSUE TITLE
Add missing @meta.orig_host_port and @meta.resp_host_port

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#112]
Please add the missing fields "@meta.orig_host_port" and "@meta.resp_host_port" that correspond to the current fields @meta.orig_host and @meta.resp_host.  

There is great hunting/data pivoting value along with both narrow your search, along with widening it.  Think bracketing with call-for-fire.  This is a general principle I teach and my team also uses it extensively.  Sometimes, you just want to simple see what records correspond to a port...

**Comment by dcode** [comment]
These fields can be found as:

```
@meta.orig_host
@meta.orig_port
@meta.resp_host
@meta.resp_port
```
