### ISSUE TITLE
How to update Snort/Suricata rules using pulledpork "offline" 

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#113]
Currently the ROCK offline ISO does not have a mechanism for updating the Snort/Suricata rules when offline, though that is the purpose of the ISO.  Also, when running ROCK offline, the cronjob for pulledpork is trying to download rules - this likely should be changed to something a bit more useful.  

Here is how JJ Cummings recommends to do this:  

   "There is a nodownload option (-n) that will allow you to perform actions on
   existing rules tarballs.  Note that the tarball must be placed where
   pulledpork would put it to run.. i.e. the temp location that is noted in the
   config file."
   http://seclists.org/snort/2011/q1/1108

./pulledpork.pl 
-n Do everything other than download of new files (disablesid, etc)
-P Process rules even if no new rules were downloaded
https://github.com/shirkdog/pulledpork

(For users of Suricata, the same steps are necessary for where your installation files reside, but all that pulledpork needs to process rule files is the -S flag being set to suricata-3.1.3 or whatever version of suricata you are using

./pulledpork.pl -c pulledpork.conf -S suricata-3.1.3)

ROCK cronjob for Pulledpork when running in offline mode, and built from the ISO with Suricata picked:  

   root /opt/pulledpork/pulledpork.pl -c /etc/pulledpork/pulledpork.conf -l > /var/log/pulledpork.log 2>&1; /usr/bin/systemctl kill -s USR2 suricata

**Comment by jeffgeiger** [comment]
The following works:  
```
cp /srv/rocknsm/support/emerging.rules-suricata.tar.gz  /tmp/emerging.rules.tar.gz

/opt/pulledpork/pulledpork.pl -c /etc/pulledpork/pulledpork.conf -S suricata-3.1.3 -n -P
```   
Looking at adding  this to the base setup now.  

The cronjob will most likely remain the same, because in the vast majority of cases, the sensor will be online.  We will add this to the documentation for offline use cases.

**Comment by bndabbs** [comment]
The Suricata role performs an update using the offline repos in current builds.
