### ISSUE TITLE
Highly incorrect instructions for online installation for ROCK 2.0:  

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#114]
The online instructions for installation of ROCK 2.0 are highly inaccurate.  

What seems to work for an "online" ROCK 2.0 installation from the ROCK 2.0 ISO:
- Install CentOS 7.3 from the ROCK 2.0 ISO
- Configure as appropriate /etc/rocknsm/config.yml 
- sudo yum update -y && reboot
- sudo yum install -y epel-release 
- sudo yum install -y git ansible 
- git clone https://github.com/rocknsm/rock.git

* The following are not located in ~/rock but:  

/opt/rocknsm/rock/ansible/generate_defaults.sh
/opt/rocknsm/rock/ansible/deploy_rock.sh

**Comment by dcode** [comment]
actually, those scripts are in ~/rock if that's where you checked out the github. Otherwise you're using the offline installed version. Your procedure wouldn't pull in new updates for the build process

**Comment by dcode** [comment]
Docs have been updated. Thanks for your contributions!
