### ISSUE TITLE
How to "re-import" raw Bro text logs into the ROCK ES database?

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#124]
How to "re-import" raw Bro text logs into the ROCK ES database?

Due to a recent accident, this would be extremely useful!  

In the case of a system failure and loss of all Elasticsearch indexes in the ROCK ES database, how would you recommend to re-import the "raw" Bro text logs back into the ROCK ES database?   This theoretically should work unless the ES database contains other types of data, such as Suricata JSON.  Lets keep it simple and assume we only have Bro logs and need to re-import.

**Comment by bndabbs** [comment]
@charlesfair I think we should leverage the snapshot capability mentioned in #31 for this. If snapshots are not configured and there is a data loss issue for whatever reason, the next best option would be to replay the raw traffic from Stenographer. This ensures that we capture the Bro *and* Suricata logs without the expense of having to parse the ASCII logs after decompressing them.
