### ISSUE TITLE
Enable SMB analyzer with default build

### ISSUE THREAD

**Issue by akniffe1** [rocknsm/rock#126]
Given the sweet value of the Bro 2.5 SMB analyzer can we get the bro RPM updated to enable this, or maybe set an ansible configuration value for "enable_smb" to add it to local.bro?

**Comment by jeffgeiger** [comment]
I think adding it to the local.bro template is the "more correct" approach rather than molesting the RPM.

**Comment by dcode** [comment]
This was closed in v2.0.2 tagged release
