### ISSUE TITLE
Mapping conflict

### ISSUE THREAD

**Issue by garanews** [rocknsm/rock#128]
Hello,
I have just installed the Rock from ISO, everything is ok but in Kibana I see this error:

Mapping conflict! 51 fields are defined as several types (string, integer, etc) across the indices that match this pattern. You may still be able to use these conflict fields in parts of Kibana, but they will be unavailable for functions that require Kibana to know their type. Correcting this issue will require reindexing your data. 

How should I fix it?

Another question: is it possible to set somewhere the retention period?
I don't know in how many days my disk will be full..
Thanks

**Comment by dcode** [comment]
@garanews, thanks for the bug report. I haven't run into this particular issue, but if you could gather some info and attach some files we can get to the bottom of it.

# Mapping Conflicts
Please run the following commands and attach each as a file:

#### All Elasticsearch mappings
```
curl localhost:9200/_mapping/_all > es_mapping.js
```

#### Elasticsearch Index templates
```
curl localhost:9200/_template > es_templates.js
```

#### Suricata Kibana index
```
curl localhost:9200/.kibana/index-pattern/suricata-* > kb_suri.js
```

#### Bro Kibana index
```
curl localhost:9200/.kibana/index-pattern/bro-* > kb_bro.js
```

# Retention Periods

There's a couple of places where you can adjust retention perdiods for data. I'll make a note that we should probably make this more streamlined.

#### Elasticsearch

Storage Location: `/data/elasticsearch`

For Elasticsearch indexes, we default to _closing_ indexes after 15 days and deleting them after 60 days. Closing the index basically makes them offline and they only use disk space (they can no longer be searched until brought online). You can adjust these values in this shell script, which is run by cron.
```
/usr/local/bin/es_cleanup.sh
```

#### Kafka

Storage Location: `/data/kafka/`

Kafka stores data in topics as a buffer, which can also be replayed to populate Elasticsearch. By default, we're saving 7 days (168 hours) of data. This can be configured in:

```
/opt/kafka/config/server.properties
```
Adjust `log.retention.hours` to specify a shorter duration. You can also set `log.retention.bytes` to specify a hard capacity limit.

#### Suricata

Storage Location: `/data/suricata/`

Suricata logs are managed using `logrotate`. You can modify the policy in `/etc/logrotate.d/suricata.conf`.

#### Bro

Storage Location: `/data/bro/logs`

Bro data is compressed at the top of each hour and rotated out to disk. We do not age off these files by default. Unless you have a very active network, they truly don't take up too much space and you can always go back and review them. If you do want to trim them down, `broctl` will handle it automatically via cron. 

You can adjust the policy in `/opt/bro/etc/broctl.cfg` by changing the value of `LogExpireInterval`. There's also `StatsExpireInterval` which will age of statistics about the bro processes.

**Comment by garanews** [comment]
Output attached.
[Documents.zip](https://github.com/rocknsm/rock/files/844870/Documents.zip)

regarding the retention, I see the script but can't find it in cron. should I add it?

**Comment by jeffgeiger** [comment]
It's picked up by cron from `/etc/cron.d/rocknsm_es_maintenance`.

**Comment by dcode** [comment]
@garanews Okay, I've been able to determine the conflicts, but I'm not sure how they got there.  Good news is that they're all in the `bro-2017.03.10` index. The data must have gotten there before the template was set, but I'm not sure how that happened. Either way, you have two options:

1. Easiest: If you don't absolutely need that day's worth of data, just delete the index and refresh Kibana
```
curl 127.0.0.1:9200/bro-2017.03.10
```
2. If you do want to retain the data, you can re-index it against the mapping. Details on that can be found in the [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html), but it goes something like this:
```
curl -XPOST 'localhost:9200/_reindex?pretty' -H 'Content-Type: application/json' -d'
{
  "source": {
    "index": "bro-2017.03.10"
  },
  "dest": {
    "index": "bro-2017.03.10-1"
  }
}
'
```
You can then delete the old index as shown in option 1.

**Comment by garanews** [comment]
Deleting the index using the first suggestion it worked. Thanks.
Another question: there is any reason to keep system in UTC?
I see that suricata logs are visualized with current time (so I can search last 15mins) instead the bro logs are logging 1 hour delayed (in the bro logs I see UTC time 1489598767.079838 5:28 pm UTC but here now 6.28 pm (gmt+1)

**Comment by dcode** [comment]
UTC is generally preferred for logging data as the timestamps from anywhere in the world will have a proper order without calculating offsets. That said, Kibana will present the bro logs according to your timezone (as set in the browser). The bro logs themselves (i.e. in `/data/bro/logs/`) log in epoch time and will be written in UTC regardless of the system timezone. Bro includes a utility for parsing these on the command line called `bro-cut`. It can be used to print human-readable timestamps in either the local sensor timezone or UTC. You can also give it a custom strftime format string to specify what you'd like displayed.

**Comment by dcode** [comment]
Closing this since the problem has been fixed. @seven62 can we get these bits added to a roadmap for the "Troubleshooting" section of the docs?

**Comment by seven62** [comment]
@dcode wilco.  I'll get more details from you soon.
