### ISSUE TITLE
Update local Repo (2.0_1703)

### ISSUE THREAD

**Issue by kazimer** [rocknsm/rock#135]
An offline installation fails when trying to configure Kibana.  The error message states that Kibana is attempting to use repoquery.  `yum-utils` and its dependencies are not installed so the repoquery fails.  The `/srv/rocknsm/Packages` does not contain the RPM either.  Will you please include this in future builds.  

Dependencies required(repoquery --requires yum-utils.noarch):

- libxml2-python
- python(abi) = 2.7
- python-kitchen
- yum >= 3.4.3-143

**Comment by dcode** [comment]
This was fixed in rocknsm/rock-createiso@9775a35e
