### ISSUE TITLE
Force user creation on ROCK install

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#146]
Sometimes new users (or developers that get distracted) will fail to create an admin user during the installation phase, resulting in an install that has no means to login. The easiest fix is to re-install from the start. This wastes time and more importantly, there's got to be a better way.

Need to find a way in anaconda to force user creation _OR_ use the firstboot scripts mechanism to finish the setup by adding a user. I like the latter, because we could leverage this in the future to kick off the install as well.

**Comment by jeffgeiger** [comment]
Fixed in rock-createiso PR # 5.

https://github.com/rocknsm/rock-createiso/pull/5
