### ISSUE TITLE
Custom install on rocknsm-2.0.5-1705.iso

### ISSUE THREAD

**Issue by ryannewlon** [rocknsm/rock#152]
Install fails when doing a custom install of rock. Reinstalled using the automatic install and it works fine.

Failed before kernel loaded so it may be during the disk partitioning.

**Comment by kwilson7770** [comment]
When installing inside of a VM the installer didn't indicate a failure, but failed to boot. It is like grub wasn't installed or something. I reinstalled with automatic, stopped the automatic installation by clicking into a menu, made the same configuration changes and the install worked just fine

**Comment by jeffgeiger** [comment]
Fixed in rock-createiso PR # 5.

https://github.com/rocknsm/rock-createiso/pull/5

**Comment by ID1010TERROR** [comment]
Having a similar issue when loading the latest release onto virtualbox. The bootloader screen loads, but selecting custom or automated install both result in the Rocknsm logo loading and the system hanging.
