### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by Fetchered** [rocknsm/rock#186]
New to RockNSM and had no real problems installing that I couldn't google solutions for, but now that I have this installed, any chance you could provide a user manual on how to use it?

First time hearing of Kibana, but it seems to be the only user interface. Don't know where I should be going to view any IDS alerts, how to configure signatures, etc.

Would appreciate more insight.

**Comment by bndabbs** [comment]
This has been addressed with https://docs.rocknsm.io/
