### ISSUE TITLE
Apply ROCK branding to Kibana interface

### ISSUE THREAD

**Issue by jeffgeiger** [rocknsm/rock#188]
Use the instructions [here](https://cinhtau.net/2017/05/10/customize-kibana-look-and-feel/) to apply RockNSM branding to the Kibana interface.

**Comment by spartan782** [comment]
Do we still want to implement this beyond the welcome dashboard in the new ECS saved objects? Or is this now deprecated or no longer needed?

**Comment by dcode** [comment]
No longer needed. Closing
