### ISSUE TITLE
Add Dependency Resolution

### ISSUE THREAD

**Issue by peasead** [rocknsm/rock#19]
CentOS-CR.repo doesn't exist until `yum update -y && yum upgrade -y`, might want to add this to the prep or the recipe. 

Also I think `yum install -y kernel-headers kernel-devel && reboot` should be part of the prep or part of the recipe.

**Comment by dcode** [comment]
We really should migrate away from CR as it is a wretched beast. I think we can safely build off 7.2. When that's confirmed we'll close this.

**Comment by dcode** [comment]
we're done with the CR repo.
