### ISSUE TITLE
GPG key task is not idempotent

### ISSUE THREAD

**Issue by bndabbs** [rocknsm/rock#190]
The following task is not idempotent: https://github.com/rocknsm/rock/blob/dcode/2.1_cleanup/playbooks/deploy-rock.yml#L120-L123

This should be replaced with the [rpm_key](http://docs.ansible.com/ansible/latest/rpm_key_module.html) module.

**Comment by dcode** [comment]
Good catch. This process needs to be cleaned up a bit anyway. I think adding the appropriate GPG keys into `/etc/pki/rpm-gpg/` does the same task and is easier to manage from an automation perspective.
