### ISSUE TITLE
Rock package does not exist

### ISSUE THREAD

**Issue by tdesrochers** [rocknsm/rock#194]
When running the installer I get the error "You have specified that the package 'rock' should be installed.  This package doesn not exist.  Would you like to ignore this package and continue with the installation?"

<img width="796" alt="screen shot 2017-11-29 at 1 03 38 pm" src="https://user-images.githubusercontent.com/9257751/33391154-295f25d8-d506-11e7-852e-e06bbbb0b3fd.png">

**Comment by tdesrochers** [comment]
This is with the nightly-20171129 build.

**Comment by bndabbs** [comment]
Rock is definitely included in the repos now.
