### ISSUE TITLE
install without user account creation

### ISSUE THREAD

**Issue by tdesrochers** [rocknsm/rock#195]
If the installer is left unattended it will complete install without a user.  

Suggestion is to configure installer to stop if no user is selected until user configures an account for the install.

**Comment by GonzoVC** [comment]
Gonzalez is working.

**Comment by jeffgeiger** [comment]
This should be fixed in the devel branch of the create_iso repo already.

https://github.com/rocknsm/rock-createiso/commit/51a6ba1d07172502706d9041cfed1bc567160c23

**Comment by GonzoVC** [comment]
Confirmed, the fix was implemented in commit above. (June 27)

**Comment by pktmterenceg** [comment]
Understanding this was closed sometime ago, I just experienced it again with the current ISO. Successfully completed the automated install with no prompts/input, only to arrive (after reboot & license acceptance) at a prompt for a user/password I didn't have. Solution was to choose custom install and try again.
