### ISSUE TITLE
Update logstash conf and ES template to only use a single doc type

### ISSUE THREAD

**Issue by bndabbs** [rocknsm/rock#197]
This is needed for Elastic 6.x

**Comment by rcgraves** [comment]
(Do you know yet) what's the general strategy here? Make a single _bro type with all fields and use @meta.event_type to distinguish? Break out each log file into its own index? (Possibly my favorite but hugely disruptive) Denormalize the data according to "The Elastic Way," i.e, merge everything with the same uid into a single document, possibly with parent/child _join (see https://discuss.elastic.co/t/parent-child-and-elastic-6/85722) for one-to-many relationships such as files?

**Comment by dcode** [comment]
@rcgraves the initial approach is to just drop the different types and use `@meta.event_type` to distinguish. Fortunately, we don't do anything with typing with our current Kibana dashboards.

I think the best possible approach, from an analytic perspective, is to merge related documents into one. For example, merge a DNS log with its respective conn log and dedupe the fields. This would be done by type/category...you can't (and shouldn't) merge the pe log entry into the http log into the conn log. You lose the ability to easily pivot across the files logs.

I've looked at the parent-child in the past and the new join fields. I think the new approach makes this an interesting thing to explore, but I don't think Kibana will do anything with it yet (it definitely wouldn't with the old construct).

**Comment by dcode** [comment]
I should add...we can't just jump the the ideal approach b/c bro produces the logs at different times so we can't merge the documents in the pipeline with logstash. It could be done after the fact through some batch jobs or in Bro itself, but we don't currently have the means to do that "live".

**Comment by bndabbs** [comment]
Updates are really expensive as well, so we wouldn't want to merge the streams together as the arrive either.

**Comment by rcgraves** [comment]
Yeah, if the grand unification is going to happen, it should be at the Bro end (defer reporting until conn.log time). It's possible we might go down that route. We are planning a green-field install and really like ES 6 for sparse and sorted indexes and a few other things, but diverging from the community data models (SOF-ELK and SO also have this issue) would suck.

**Comment by bndabbs** [comment]
This is the current config I have for logstash: https://gist.github.com/bndabbs/1a073529d43079578864d139c8a3ea4b

It moves most log streams to their own index to avoid sparse fields. Some of the lesser used streams, like the diagnostic ones, are kept in a single index.
