### ISSUE TITLE
Determine and tool a method to update existing stacks to Elastic 6.x 

### ISSUE THREAD

**Issue by bndabbs** [rocknsm/rock#198]
Main thing here is to update the existing ES mapping template and re-index existing data.

**Comment by bndabbs** [comment]
This will come into play for the indexes https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

**Comment by grantcurell** [comment]
Me and another dude were going to take a look at this when I finish the role migration. Have you already started this?
