### ISSUE TITLE
RockNSM needs to add support for Python3

### ISSUE THREAD

**Issue by grantcurell** [rocknsm/rock#205]
The existing code for doing this is attached. It needs to be ported into Ansible and become part of the standard install. The package pulled by the RPM is out of date.

Edit: For clarity, you can install Python3 via the Red Hat repos, but it's like Python 3.4 I think and they're on 3.6.

[090_common_python3_install.sh.txt](https://github.com/rocknsm/rock/files/1551969/090_common_python3_install.sh.txt)

**Comment by dcode** [comment]
We don't install things from source packages. It makes for a messy, unmaintainable enterprise platform. We fix the RPM. Specifically for Python3. What is the Python version requirement and for what? Software Collections may be a viable option.

**Comment by dcode** [comment]
After offline discussion, this may not be needed. If it is still needed, we'll explore using Software Collections to meet the need.

**Comment by grantcurell** [comment]
Agreed
