### ISSUE TITLE
Rock needs the option to install a portainer container

### ISSUE THREAD

**Issue by grantcurell** [rocknsm/rock#211]
Like https://github.com/rocknsm/rock/issues/207, Portainer should be an available piece of software for installation on the system.

Requirements:
- Add Portainer to the install if an option is set to true in https://github.com/rocknsm/rock/blob/master/playbooks/vars/rocknsm_config.dist.yml
- If portainer is enabled, then sensor nodes should be set to have port 2375 open so that Docker may be managed.

**Comment by dcode** [comment]
See my comments on #207. I think a possible alternative to meeting a similar use-case for sensor-only installs would to use [Cockpit](http://cockpit-project.org/). This is super lightweight for system management, including docker. It's probably not as powerful for multi-host docker deployments, but it probably adds value beyond that for lightweight installs. This is up for discussion.

**Comment by grantcurell** [comment]
I'll get with you in dev - right now I won't be able to make that swap

**Comment by grantcurell** [comment]
Jason knocked this one out.
