### ISSUE TITLE
Make ROCK a cleaner install via RPM

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#218]
[kolla-ansible](https://git.openstack.org/cgit/openstack/kolla-ansible/) provides a clean wrapper script for ansible with pre-specified actions for installation and removal. They also have a clean approach to multiple playbooks that we should adopt. This becomes more important as we move to a multi-host deployment.

**Comment by dcode** [comment]
Here's their wrapper script, for example: https://github.com/openstack/kolla-ansible/blob/master/tools/kolla-ansible

**Comment by bndabbs** [comment]
We now have a ROCK RPM and a wrapper script that addresses this.
