### ISSUE TITLE
the directory /opt/bro/share/bro/site/scripts/rock is not empty, refusing to convert it

### ISSUE THREAD

**Issue by grantcurell** [rocknsm/rock#222]
While running the grantcurell-addingroles branch, the offline bro task "Symlink offline Rock bro scripts" files with:

```
TASK [bro : Symlink offline ROCK bro scripts] ***************************************************************************************************************
fatal: [simplerockbuild.simplerock.lan]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "the directory /opt/bro/share/bro/site/scripts/rock is not empty, refusing to convert it", "owner": "root", "path": "/opt/bro/share/bro/site/scripts/rock", "secontext": "unconfined_u:object_r:usr_t:s0", "size": 201, "state": "directory", "uid": 0}
```

I haven't had the chance to troubleshoot why. Any help appreciated.

Path: playbooks/roles/bro/tasks/main.yml

**Comment by Duckmanjbr** [comment]
I think this is part of a bigger problem.  I reached out to Derek to understand his deployment intent.  It looks like this is designed to run local Bro scripts that have been pre-downloaded (possibly on the .iso install).  I've fixed by adding a check before running a few items in the playbook.
