### ISSUE TITLE
Need to integrate generate_defaults with the role based build

### ISSUE THREAD

**Issue by grantcurell** [rocknsm/rock#223]
Moving files and variables around into their respective roles has broken generate_defaults. Need to go back and repair those dependencies. Problem can be seen in the "Render template" task of generate_defaults because the bro_cpu variable has been moved to a role.

**Comment by Duckmanjbr** [comment]
Updated generate_defaults to pull variables from each role folder.  Roles are lowest priority in variables so if needed variable can be overwritten by higher power.
