### ISSUE TITLE
Zookeeper fails to start

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#230]
zookeeper rpm installs, but the service fails because it cannot open the environment file located at `/etc/zookeeper/java.env`. This should be included in the package, because I think it also specifies the classpath.

**Comment by elastickent** [comment]
Fixed it locally with:

`[Service]
User=zookeeper
Group=zookeeper
SyslogIdentifier=zookeeper
EnvironmentFile=/etc/sysconfig/zookeeper
ExecStart=/usr/bin/java \
  -Dzookeeper.log.dir=/var/log/zookeeper \
  -Dzookeeper.root.logger=${LOG4J} \
  -cp "/usr/share/java/zookeeper/zookeeper-3.4.11.jar:/usr/share/java/zookeeper/*" \
  -Dlog4j.configuration=file:/etc/zookeeper/log4j.properties \
  -Dcom.sun.management.jmxremote \
  -Dcom.sun.management.jmxremote.local.only=false \
    org.apache.zookeeper.server.quorum.QuorumPeerMain \
  /etc/zookeeper/zoo.cfg
`

**Comment by bndabbs** [comment]
This was fixed with: https://github.com/rocknsm/rpms/commit/a22dcc4493e587d93070367362ca592497be0e13
