### ISSUE TITLE
Yara dependency - Centos 7

### ISSUE THREAD

**Issue by anlx-sw** [rocknsm/rock#238]
When doing a manual installation of rocknsm on centos 7 it is required to add the "EPEL" repo (as described in the documentation)
The EPEL repo provides yara in version 3.7 currently.

The rocknsm repo provides yara 3.4 which is also a dependency for fsf:
```
 Resolving Dependencies
--> Running transaction check
---> Package yara.x86_64 0:3.4.0-1 will be updated
--> Processing Dependency: yara = 3.4.0 for package: fsf-1.1-1.20170223git3de1496.el7.centos.x86_64
---> Package yara.x86_64 0:3.7.0-1.el7 will be an update
--> Finished Dependency Resolution
Error: Package: fsf-1.1-1.20170223git3de1496.el7.centos.x86_64 (@rocknsm)
           Requires: yara = 3.4.0
           Removing: yara-3.4.0-1.x86_64 (@rocknsm)
               yara = 3.4.0-1
           Updated By: yara-3.7.0-1.el7.x86_64 (epel)
               yara = 3.7.0-1.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Whenever doing a `yum update` the above error is shown.

To work arround this problem the yara package from the epel repo can be blacklisted by editing  `/etc/yum.repos.d/epel.repo` and adding `exclude=yara*`  in the `[EPEL] `section

As i couldn't find a solution to this problem by searching the issues and by googling i thought i post this for others with the same problem.

**Comment by dcode** [comment]
thanks @anlx-sw! This is a good temporary work around. We're going to update the FSF package to work with the latest upstream yara. We've tested this and verified it works now.

**Comment by bndabbs** [comment]
Fixed here: https://github.com/rocknsm/rpms/commit/b2570a28c9964d3c53ebfcef6b7c01e920534ace#diff-5e374134030707af12e0329d6eba9728R45
