### ISSUE TITLE
Suricata Permissions Issue

### ISSUE THREAD

**Issue by jdpadro** [rocknsm/rock#248]
OK so I added the "" and reran status on suricate which show on permission issue

Feb 21 10:12:49 cs-hog-xxx05 suricata[7466]: 21/2/2018 -- 10:12:49 - - [ERRCODE: SC_ERR_DEPRECATED_CONF(274)] - deprecated 'force-md5' option found. Please use 'force-hash: [md5]' instead
Feb 21 10:12:49 cs-hog-xxx05 suricata[7466]: 21/2/2018 -- 10:12:49 - - [ERRCODE: SC_ERR_INITIALIZATION(45)] - Unix socket: UNIX socket bind(/var/run/suricata/suricata-command.socket) error: Permission denied
Feb 21 10:12:49 cs-hog-xxx05 suricata[7466]: 21/2/2018 -- 10:12:49 - - [ERRCODE: SC_ERR_INITIALIZATION(45)] - Unable to create unix command socket

**Comment by dcode** [comment]
This requires some updates to either the Suricata package, the RockNSM ansible scripts that configure Suricata, or both.

- [ ] The systemd service file should create `/run/suricata/` with permissions of `suricata:suricata`
- [ ] Need to update the config to use the updated `force-hash: [md5]` for the 4.0.4 version

**Comment by dcode** [comment]
@jdpadro this issue still lingered on the devel branch. I pushed a fix that I think fully fixes the runtime directory issue in 44974f01. I pushed the RPM to the testing repos and it should be in the next ISO nightly.
