### ISSUE TITLE
@meta. fields change

### ISSUE THREAD

**Issue by ZewUser** [rocknsm/rock#263]
Having to type "@meta.<field_name>" for the meta fields is 5 extra characters. typing just "@<field_name" would retain 100% functionality but save 5 keystrokes.

currently sitting through a 5 day class on Rock and tired of miss-typing "@meta."

**Comment by dcode** [comment]
@ZewUser good news is, we're going to move away from "@meta". Bad news is (with regards to field length), we're moving towards the Elastic Common Schema. This will put data in each of its own respective namespaces. The flip side good news is, Kibana is implementing features that will make it less tedious to type long field names, namely auto complete and abbreviated names where possible.
