### ISSUE TITLE
Ansible Failing During Deployment

### ISSUE THREAD

**Issue by exZACHly** [rocknsm/rock#266]
Performing the installation and deployment per instructions yields the following Ansible error when using the deploy script:

`fatal: [simplerockbuild.simplerock.lan]: FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on (#!/bin/bash\n# File: /sbin/ifup-local\n#\n#\n# This script is run after normal sysconfig network-script configuration\n# is performed on RHEL/CentOS-based systems.\n#\n# Parameters:\n# $1: network interface name\n#\n# Post ifup configuration for tuning capture interfaces\n# This is compatible with the ixgbe driver, YMMV\n\n# Change this to something like /tmp/ifup-local.log for troubleshooting\nLOG=/dev/null\n#LOG=/tmp/ifup-local.log\n\ncase $1 in\n{{ rock_monifs | list | join('|') }})\n\n  for i in rx tx sg tso ufo gso gro lro rxvlan txvlan\n  do\n    ethtool -K $1 $i off &>$LOG\n  done\n\n  ethtool -N $1 rx-flow-hash udp4 sdfn  &>$LOG\n  ethtool -N $1 rx-flow-hash udp6 sdfn &>$LOG\n  ethtool -n $1 rx-flow-hash udp6 &>$LOG\n  ethtool -n $1 rx-flow-hash udp4 &>$LOG\n  ethtool -C $1 rx-usecs 10 &>$LOG\n  ethtool -C $1 adaptive-rx off &>$LOG\n  ethtool -G $1 rx 4096 &>$LOG\n\n  # Disable ipv6\n  echo 1 > /proc/sys/net/ipv6/conf/$1/disable_ipv6 &>$LOG\n  echo 0 > /proc/sys/net/ipv6/conf/$1/autoconf &>$LOG\n\n  # Set promiscuous mode\n  ip link set $1 promisc on &>$LOG\n\n  # Just in case ipv6 is already on this interfaces, let's kill it\n  ip addr show dev $1 | grep --silent inet6\n\n  if [ $? -eq 0 ]\n  then\n    ADDR=$(ip addr show dev $1 | grep inet6 | awk '{ print $2 }')\n    ip addr del $ADDR dev $1 &>$LOG\n  fi\n\n;;\n\n*)\n# No post commands needed for this interface\n;;\n\nesac\n): 'NoneType' object is not iterable"}`

**Comment by spartan782** [comment]
Are you installing this using a VM on a windows OS?

**Comment by exZACHly** [comment]
Yes, I am. Are there issues with that?

**Comment by spartan782** [comment]
There is, I thought I had created an issue for it but it looks I failed. The Windows OS doesn't seem to play well with making any changes to the interface so the `ifup-local` script fails. I was not tracking this on ESXi though so thats also good to know. This can be worked around by modifying the ansible script, but there is multiple pieces that fail.

**Comment by danpoleary1** [comment]
I am having the same issue on ESXi. What is the solution to pass this step?

**Comment by dcode** [comment]
In ESXi you need to ensure that the NIC has permission to do promiscuous
mode. You can grant that in the properties for that NIC specifically
(recommended) or grant that in the network segment definition for all VMs.

**Comment by danpoleary1** [comment]
In my ESXi I have the vswitch in promiscuous mode and that works with other virtual machines on the same vswitch for sniffing and packet capture.

I have two interfaces in the Rock vm. Should I rename them? or keep the default VMware naming?

**Comment by danpoleary1** [comment]
Well, solved my own problem. I had to delete the default route on the 2nd interface, and then add that interface to the config.yml.

Had to dig through docs. Should have a default set of steps for deploying the vm instance.
