### ISSUE TITLE
Source '/srv/rocknsm/support/rock-dashboards_devel.tar.gz' does not exist

### ISSUE THREAD

**Issue by seven62** [rocknsm/rock#276]
`fatal: [simplerockbuild.simplerock.lan]: FAILED! => {"changed": false, "msg": "Source '/srv/rocknsm/support/rock-dashboards_devel.tar.gz' does not exist"}`  

I can't find where this is called out right now; but I didn't have time to look outside of /opt/rocknsm/

**Comment by dcode** [comment]
This is covered by the `offline-snapshot.sh`. @spartan782 is porting this to ansible and will be pulling the devel until we snapshot everything to master.

**Comment by jeffgeiger** [comment]
This seems to be working in the current builds. Not sure which commit to reference, but tagging as awaiting merge.
