### ISSUE TITLE
Failed: TASK [Blanket install/update Kibana saved objects]

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#281]
For some reason the following is failing on a clean install. Still trying to figure it out.

```
/import-saved-items.sh http://127.0.0.1:5601
```

That happens here: https://github.com/rocknsm/rock/blob/devel/playbooks/deploy-rock.yml#L423-L430

**Comment by raulnor516** [comment]
Running deploy_rock.sh after migrating the VM from Workstation to an ESXi server and increasing hardware leads to this task still getting stuck. The "Wait for Kibana to be available" task completed correctly, but the following "Blanket Install" task is still stopping progress from building after the migration.

**Comment by dcode** [comment]
@raulnor516 try the ISO here. I built it yesterday and we're doing a sprint to knock out all the bugs. This isn't guaranteed bug free, but it runs to completion. I would welcome your feedback and testing: https://drive.google.com/drive/folders/1rQ_5FnPWPZOQOU2a-Cyv6uHfNufhw6lb?usp=sharing

**Comment by raulnor516** [comment]
Issue was caused by adding additional storage to /data and not rebooting prior to running deploy_rock.sh. Restarting elasticsearch and kibana services multiple times seemed to fix the issue, but restarting is the smarter option. Issue closed.
