### ISSUE TITLE
Kibana fails to create saved objects

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#304]
Version: 2.1.0
ISO Build: 20180821-0944

On the latest ISO (2.1) tested in a VM, Kibana failed to correctly create the saved objects. When manually trying to create an index pattern in Kibana, it also fails with a status code of 400 (see below). I reinstalled the VM using the automated method and ran the deploy w/o further configuration. I also tried turning off the firewall and going directly to the 5601 port, with the same results as the 443 reverse proxy.

![image](https://user-images.githubusercontent.com/171574/44480836-fb777480-a5df-11e8-895b-3b35481dd70d.png)

Text:
```
Error: Request failed with status code: 400
    at http://192.168.100.131:5601/bundles/commons.bundle.js:3:885543
    at tryCatch (http://192.168.100.131:5601/bundles/vendors.bundle.js:133:364589)
    at Generator._invoke (http://192.168.100.131:5601/bundles/vendors.bundle.js:133:366664)
    at Generator.prototype.(anonymous function) [as next] (http://192.168.100.131:5601/bundles/vendors.bundle.js:133:364873)
    at step (http://192.168.100.131:5601/bundles/commons.bundle.js:3:884573)
    at http://192.168.100.131:5601/bundles/commons.bundle.js:3:884700
```

**Comment by spartan782** [comment]
There doesn't appear to be a .kibana index. Which when I try to create it manually it spits out the following.
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Rejecting mapping update to [.kibana] as the final mapping would have more than 1 type: [_doc, doc]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Rejecting mapping update to [.kibana] as the final mapping would have more than 1 type: [_doc, doc]"
  },
  "status": 400
}
```

**Comment by spartan782** [comment]
There also appears to be 2 templates for the .kibana index. 
1. kibana-config
2. kibana_index_template:.kibana

The second appears to be created each time the UI is used to create an index pattern. I have tried deleting both of them and still get the 400 error when creating an index pattern. 

When they are both deleted I can create a `.kibana` index manually but that does not fix the issue either. When the second template is generated it again causes issues.
