### ISSUE TITLE
Remove nginx in favor of lighttpd

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#309]
Right now we use two webservers and that's a bit silly. Nginx has served us well (no pun intended), but it's a pain to maintain and it pulls in the `fontconfig` package, for whatever reason. This adds half a gig (at least) of fonts to the release ISO and we're squashing it.

Long live lighttpd! Coming soon to a release near you.

**Comment by dcode** [comment]
Here's all the configs: https://gist.github.com/dcode/3947884b4b2a4754e9538b307894ef03

**Comment by bndabbs** [comment]
This is complete
