### ISSUE TITLE
Include capability to export indexes for archiving

### ISSUE THREAD

**Issue by jeffgeiger** [rocknsm/rock#31]
To free space on ROCK without without permanently losing data, include or document a method to export indexes from elasticsearch. Should also be able to import previously exported data.

Added bonus: This would allow Kibana dashboards to be exported and imported.

**Comment by dcode** [comment]
Kibana dashboards can now be imported/exported at will. I think the `es_cleanup.sh`. Elasticsearch also supports "snapshots" which are compressed and contain all index data for this use-case. Do we need to further wrap that capability?

**Comment by bndabbs** [comment]
I agree that snapshots are a recommended approach here. I don't think this is something we should try to automate though, since the snapshot destination will be environment dependent. 

Can this issue be closed?
