### ISSUE TITLE
RockNSM 2.2

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#315]
Checklist

- [ ] Integrate Elastic Stack 6.4
- [ ] More ECS work
  - See #311, #312, #313 
- [ ] Switch to Lighttpd for all reverse proxying
  - See #309 
- [ ] Reduce filesize to less than 2GB
  - See #309 
- [ ] Update Suricata rule support to use `suricata-update`
- [ ] Integrate "Slurpy" as a PCAP ingest and playback tool.

**Comment by kevinkeeneyjr** [comment]
6.4.1 was released: https://www.elastic.co/guide/en/kibana/6.4/release-notes-6.4.1.html

**Comment by bndabbs** [comment]
2.2 is out.
