### ISSUE TITLE
Running suricata-update -s does not reload suricata

### ISSUE THREAD

**Issue by raulnor516** [rocknsm/rock#318]
I ran `sudo suricata-update -s /home/user/rules` (containing the suricata ET ruleset included on the ISO). The update ran successfully, showing that the rules were loaded. Suricata was not actually processing the rules though, requiring a restart before they took affect.

**Comment by jeffgeiger** [comment]
You can run `sudo /usr/bin/systemctl kill -s USR2 suricata` after the update to bump suricata and make it reload it's rules. I'm going to work on making the offline build automatically pull in the `/srv/rocknsm/support` rules at build time.

**Comment by jeffgeiger** [comment]
Hoping to roll this and #317 into one fix. Good catch.
