### ISSUE TITLE
Dependency resolution error - uwsgi-plugin-python for docket-1.0.1-3

### ISSUE THREAD

**Issue by wesleyraptor** [rocknsm/rock#319]
ISO: rocknsm-2.1.0.iso

Installed the ISO on a server and I was trying to do an online install of the RockNSM software via the deployment script at /opt/rocknsm/rock/bin/deploy_rock.sh, and it fails due to a dependency resolution error while trying to install the docket package:

``
--> Finished Dependency Resolution
Error: Package: docket-1.0.1-3.noarch (rocknsm-local)
           Requires: uwsgi-plugin-python
           Available: uwsgi-plugin-python-2.0.16-1.el7.x86_64 (rocknsm-local)
               uwsgi-plugin-python = 2.0.16-1.el7
``

The software cannot be installed without resolving this dependency resolution error.

**Comment by dcode** [comment]
Can you give the output of `yum install uwsgi-plugin-python` ?

**Comment by dcode** [comment]
@wesleyraptor I found the issue. Upstream EPEL packages renamed `uwsgi-plugin-python` to `uwsgi-plugin-python2` and didn't provide a clear upgrade path. I'll rebuild the Docket RPM with the newly changed name and that will fix this. In the meantime, you could install uwsgi-plugin-python and related uwsgi packages from the RockNSM ISO.
