### ISSUE TITLE
RockNSM fails to install due to bind-libs

### ISSUE THREAD

**Issue by kvv5150** [rocknsm/rock#322]
Bro fails to install in the Optional packages task. Due to bind-libs

Error: Package: 32:bind-libs-9.9.4-61.el7.x86_64 (rocknsm-local)
           Requires: bind-license = 32:9.9.4-61.el7
           Installed: 32:bind-license-9.9.4-61.el7_5.1.noarch (@updates)
               bind-license = 32:9.9.4-61.el7_5.1
           Available: 32:bind-license-9.9.4-61.el7.noarch (rocknsm-local)
               bind-license = 32:9.9.4-61.el7

Attempted install on VMWare Workstation this morning with the Rock ISO

**Comment by kwright5150** [comment]
Seems to be an issue with Rock's local repo. After testing the online install it worked fine. This may be intended?

**Comment by dcode** [comment]
@kwright5150 The issue here is that the package in EPEL was updated and changed it's structure since the time we released the ISO, which is the problem. And it's really frustrating. If you do a complete offline install, it works. There is an online work around that I figured out a couple weeks ago. I'll post the fix here, hopefully later today.

**Comment by kvv5150** [comment]
That's odd because exactly the opposite happened in my tests. I left settings to default in the config (offline install) and it failed. Performed a different test with online config and it worked flawlessly. Anyway, you can close this issue since changing it fixed my issue.

**Comment by T3chGuy77** [comment]
> @kwright5150 The issue here is that the package in EPEL was updated and changed it's structure since the time we released the ISO, which is the problem. And it's really frustrating. If you do a complete offline install, it works. There is an online work around that I figured out a couple weeks ago. I'll post the fix here, hopefully later today.

Can you post the work around please. I am having this issue and this is holding me up from getting it all up and working. Thanks!

**Comment by kvv5150** [comment]
@T3chGuy77 can you run the install online? If so, edit the config on line 30

30 rock_online_install: False  <<<- change this to **True**
