### ISSUE TITLE
RockNSM nightly fails to initialize suricata rules

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#323]
`suricata-update` failed to update the rules without syncing down the index maintained by OISF first. I ran the following and re-ran the deploy to success.

```
# Need to run update-sources first
sudo -u suricata -g suricata /usr/bin/suricata-update update-sources
```

Need to put this step in on the first run of `suricata-update`.

**Comment by bndabbs** [comment]
`update-sources` is included in the suricata role currently.
