### ISSUE TITLE
@meta.related_ips remove duplicates

### ISSUE THREAD

**Issue by neu5ron** [rocknsm/rock#334]
It creates duplicates. Since there is no distinction of the IPs in terms of direction/source (there doesn't need to be for this use case) it would make sense to perform a unique in either the logstash pipeline or via ES mapping.

**Comment by dcode** [comment]
Good point.  I'll add that here on the ECS mappings. It'll be a single set operation in ruby. 
 https://github.com/rocknsm/rock-dashboards/blob/master/ecs-configuration/logstash/conf.d/logstash-900-filter-ecs-enrich.conf

**Comment by spartan782** [comment]
Implemented in rock-dashboards repo
