### ISSUE TITLE
index mappings

### ISSUE THREAD

**Issue by neu5ron** [rocknsm/rock#335]
I am sure there is probably many more too ad or possibly even you all are tracking, but first glance here is some fields that (by default) do not have mappings:

- [ ] ssl.ja3
- [ ] ssl.ja3s
- [ ] @meta.related_ips

**Comment by dcode** [comment]
All future ELK pipeline work will align with ECS. Can you load these configs and go from there?

https://github.com/rocknsm/rock-dashboards/tree/master/ecs-configuration
