### ISSUE TITLE
[2.3][beta] Variable is missing for Filebeat

### ISSUE THREAD

**Issue by bndabbs** [rocknsm/rock#341]
This is related to #328. We just need to add `enable_filebeat:` to the default vars.

```
TASK [suricata : Enable and start filebeat] ******************************************************************************************************************
fatal: [simplerockbuild.simplerock.lan]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'enable_filebeat' is undefined\n\nThe error appears to have been in '/opt/rocknsm/rock/playbooks/roles/suricata/tasks/main.yml': line 49, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable and start filebeat\n  ^ here\n"}
```

**Comment by dcode** [comment]
Specifically, I think it needs added to the configuration template. I talked to @seven62 about this when he was updating the documentation. It might simplify things to adopt similar how to Elastic does it with a `rocknsm.reference.yml` that has all the options and documentation of them, and a `rocknsm.yml` that has just what's changed. The `generate-defaults` could then run a playbook that parses in the reference config as a dictionary (loading the yaml), merge in values from the `group_vars`, and write a straight YAML out to `rocknsm.yml`. The downside of this is that it doesn't preserve comments. If we really wanted to preserve the comments, there's a [Python module](https://stackoverflow.com/questions/7255885/save-dump-a-yaml-file-with-comments-in-pyyaml) out there we could co-opt to do the merging and output.
