### ISSUE TITLE
config.yml specifies inaccurate deploy_rock script location

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#369]
At the end of file /etc/rocknsm/config.yml the operator is instructed:

NEXT STEP: Deployment
Once the settings in this config file have been finalized, the next step is to run the "deploy_rock" script located at:

   /opt/rocknsm/rock/bin/deploy_rock.sh

The actual location of deploy_rock.sh is:
   /usr/sbin/deploy_rock.sh

This could be an issue for inexperienced RockNSM users, or users new to Linux. Suggest either changing the config.yml file, or creating a symlink to the new location of the script at the original location.

**Comment by peasead** [comment]
PR #370
