### ISSUE TITLE
generate-defaults playbook ignores existing config values

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#376]
The `generate-defaults.yml` playbook also ignores existing config values. This presents itself when trying to deploy a strictly offline sensor, unless the user manually sets `rock_online_install` to `False`, it will fail to reach out to pull down the CentOS GPG keys.

Suggest adding the following to `generate-defaults.yml` playbook (same solution as #349)

```
  vars_files:
    - /etc/rocknsm/config.yml
```

Alternatively, we could pass in the existing config as extra vars in the generate_defaults shell script.

**Comment by bndabbs** [comment]
I think what needs to happen is just remove `- import_playbook: generate-defaults.yml` from [site.yml](https://github.com/rocknsm/rock/blob/211c5099978fce2af8e573fccc92e77ce40ddc5c/playbooks/site.yml#L2). 

The generate defaults playbook should only be run on initial installation or if you need to reset your config. Maybe I'm misunderstanding, but I don't think it makes sense to consider user overrides in the event that they want to reset to defaults.

**Comment by bndabbs** [comment]
We also need to update [this section](https://github.com/rocknsm/rock-createiso/blob/a76603202f17e07c84f12579479a5684175c6be9/ks/install.ks#L74-L81) to set `rock_online_install: False` **after** generating defaults the first time.

**Comment by bsolomon1124** [comment]
It appears this wasn't really updated in the [docs](https://docs.rocknsm.io/configure/reference/#offline)

... or, at least, that section of the docs is not really clear about what "our next release" is.

Suggestion - something like:

> **Changed in version x.y.z: the default `rock_online_install` is now `False`.
