### ISSUE TITLE
Don't clobber centos repos

### ISSUE THREAD

**Issue by spartan782** [rocknsm/rock#380]
We should add a check of some sort, open to discussion. My suggestion.
>>>
IF 
rock_online_install: True 
rock_disable_offline_repo: True 
files already exist in /etc/yum.repos.d/ 
then we skip this task.

https://github.com/rocknsm/rock/blob/211c5099978fce2af8e573fccc92e77ce40ddc5c/roles/common/tasks/configure.yml#L194-L206

**Comment by dcode** [comment]
I've got a fix for this pending. I'll be using the `ini_file` module instead. It's much cleaner for these existing repo files.
