### ISSUE TITLE
Hardware dependent vars should be generated from hosts where used

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#386]
In a multinode setup, the vars in `/etc/rocknsm/config.yml` are populated from the deployment host only. To correctly allow for multinode deployment, these vars should be derived from the hardware upon which they're used.

Specifically, the `es_mem` var will use half of the available RAM. In my example, I had a 32 GB deployment host, but only a 16 GB elasticsearch host. Of course, this caused Elasticsearch to be configured to memlock 16GB, which fails.

**Comment by bndabbs** [comment]
Currently tracking:

```
rock_monifs
bro_cpu
es_mem
es_node_name
```

**Comment by bndabbs** [comment]
Fixed with e754ca1bf11de073582e7819d1480fe370a022f2
