### ISSUE TITLE
Add an option to update dashboards

### ISSUE THREAD

**Issue by bndabbs** [rocknsm/rock#397]
It would be helpful to have an option in [rock](https://github.com/rocknsm/rock/blob/dfc3088e260b99584c8f3a25103658399f4d1961/bin/rock) to pull in any changes from [rock-dashboards](https://github.com/rocknsm/rock-dashboards).

Something to the effect of: `rock update-dashboards`

**Comment by neu5ron** [comment]
agreed!
as we are working this stuff discussed early today around ECS and such -- this work will make this easier.
we need the data tables and stuff first, out of yml or csv/spreadsheet -- so we can then programmatically do this.
let me know if you want to discuss more
