### ISSUE TITLE
Elastic repo needs to reference vars for version

### ISSUE THREAD

**Issue by bndabbs** [rocknsm/rock#399]
https://github.com/rocknsm/rock/blob/dfc3088e260b99584c8f3a25103658399f4d1961/roles/common/tasks/configure.yml#L112-L119

The vars are already in playbooks/group_vars/all.yml, we just need to make use of them.

**Comment by dcode** [comment]
The `elastic_baseurl` does take this into account, but it would be good to update the name and description.

https://github.com/rocknsm/rock/blob/dfc3088e26/playbooks/group_vars/all.yml#L101

**Comment by bndabbs** [comment]
Fixed with #435
