### ISSUE TITLE
sensor_logtype:conn field:duration being incorrectly indexed as string value, not number.

### ISSUE THREAD

**Issue by TravisEminhizer** [rocknsm/rock#41]
The duration field is being indexed and valued, but as an individual "string" such as 0.0000986, 0.0000987, etc.

This is crippling because you can't visualize strings over time due to obvious reasons.﻿

Side Note: Using Offline ISO Installation Build.

**Comment by dcode** [comment]
Closing this as in 2.0 this is no longer an issue.
