### ISSUE TITLE
GC log setting in environment file breaks Kafka

### ISSUE THREAD

**Issue by kwbyron** [rocknsm/rock#462]
In the environment file for Kafka's service (/etc/sysconfig/kafka), GC logging is set with the line "KAFKA_GC_LOG_OPTS=-Xlog:gc:/var/log/kafka/kafkaServer-gc.log -Xlog:gc*" which breaks Kafka with unknown settings. 

Removing the ":" and the second setting to read as 
"KAFKA_GC_LOG_OPTS=-Xloggc:/var/log/kafka/kafkaServer-gc.log" seems to fix it.

**Comment by neu5ron** [comment]
@kwbyron are you able to explain how this becomes broken? latest version of Rock doesn't appear to have this issue with Kafka not working - but I may be misunderstanding you.

**Comment by neu5ron** [comment]
fixed using java 11
