### ISSUE TITLE
Need version number when installing rocknsm dependencies

### ISSUE THREAD

**Issue by jokvedaras** [rocknsm/rock#497]
In my use case, we are approved to use a specific version of rocknsm and all of it's dependencies at that point in time.  A lot of the dependencies are included. and stable, within the rocknsm_2_4 (or whatever version you are using) repository but we run into an issue with the elastic software.  Since rocknsm uses the elastic-7x repo, rocknsm will automatically update to the latest elastic software and sometimes the code I branched from is incompatible w/ that version. I propose we add version tags to the elastic software install tasks.  Additionally, it may be worthwhile to add the elastic software to the rocknsm yum repository.

**Comment by spartan782** [comment]
I don't think it is a good idea to pin our online install to specific versions as it would cause issues for people on the other side of the fence that want to be able to get more updated packages when online install is available. 

My recommendation would be to set the rock deploy scripts to OFFLINE mode which would then us the packages on the ISO which are pinned to what ever the current stable working version at the time of that ISO release.

**Comment by jokvedaras** [comment]
I understand that viewpoint.  This wouldn't lock you into that version because after the first 'yum update' it will download and install the latest if you have the elastic repository configured.  Adding the version number is an indication that rocknsm is supported up to that elastic version.  If you upgrade, it might have unintended consequences as it was not tested by the team yet.

**Comment by bndabbs** [comment]
It's worth noting that Elastic supports version locking in their Ansible role as well https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/elasticsearch-RedHat-version-lock.yml. 

I am in favor of adding a similar logic into ROCK.

**Comment by spartan782** [comment]
I am closing this issue. In our 3.0 release we are working toward we will be implementing version pinning/customization for all of the components not just elastic. #575
