### ISSUE TITLE
rock-release missing from package cloud

### ISSUE THREAD

**Issue by grantcurell** [rocknsm/rock#513]
Package cloud doesn't have the Rock 2_5 rock-release rpm present. Installation fails with:

"You have specified that the package 'rock-release' should be installed. This package does not exist. would you like to ignore this package and continue with the installation?"

Fix action:

When creating the ISO, cd to rocknsm_cache/Packages/ and run:
`wget --content-disposition https://packagecloud.io/rocknsm/2_4/packages/el/7/rock-release-2.4-1.noarch.rpm/download.rpm`

Create ISO as normal afterwards.

**Comment by spartan782** [comment]
Fix for this
https://github.com/rocknsm/rpms/pull/45

**Comment by peasead** [comment]
Addressed by @spartan782
