### ISSUE TITLE
Single Node Deployment failure

### ISSUE THREAD

**Issue by chris-ratliff** [rocknsm/rock#519]
Trying to do a virtual installation and after following the step on https://docs.rocknsm.io/deploy/single-node/ I get:

TASK [common : Add the inventory into /etc/hosts] **********************************************************************************************************************
fatal: [rock01.rock.lan]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'address'\n\nThe error appears to have been in '/usr/share/rock/roles/common/tasks/configure.yml': line 91, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add the inventory into /etc/hosts\n  ^ here\n"}

/usr/share/rock/roles/common/tasks/configure.yml looks like this:

    91  - name: Add the inventory into /etc/hosts
    92    lineinfile:
    93      dest: /etc/hosts
    94      regexp: '.*{{ item }}$'
    95      line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
    96      state: present
    97    when: hostvars[item]['ansible_facts']['default_ipv4'] is defined
    98    loop: "{{ groups['all'] }}"

This is the first time I've tried the build.. Any ideas?

**Comment by dcode** [comment]
@chris-ratliff just circling back to this. Did you fix the problem?

**Comment by chris-ratliff** [comment]
@dcode aye, was user error. the address variable was undefined because the rock setup script didnt write the address variable since i didnt enter a valid gateway. i ended up manually assigning the ip address outside of the script and didnt realize the ansible variable was only written at script time. thanks for the checkup.
