### ISSUE TITLE
Add js3 Application Enrichment

### ISSUE THREAD

**Issue by peasead** [rocknsm/rock#521]
Use ja3er to enrich ja3 hashes. Probably something that would need to be enabled (disabled by default) because it reaches out to the Internet. 

Rest API
`curl -X GET 'https://ja3er.com/search/[md5_hash]'`

Or an Ajax call with jq 
`$.getJSON( "https://ja3er.com/json", function( json ) {
  console.log( "JSON Data: " + json.ja3 );
 });`

https://ja3er.com/docu.html

**Comment by peasead** [comment]
I think we could do this with the Logstash [HTTP Filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-http.html)

**Comment by akniffe1** [comment]
Hey @peasead there's a full list download too. It might not be too difficult to do an offline lookup against this: https://ja3er.com/getAllHashesJson

**Comment by peasead** [comment]
> Hey @peasead there's a full list download too. It might not be too difficult to do an offline lookup against this: https://ja3er.com/getAllHashesJson

NOICE!

Even better.

**Comment by akniffe1** [comment]
wow, that's quite disparity. Good find man, that's a big deal

**Comment by stevewillson** [comment]
https://ja3er.com/getAllHashesJson shows the "User-Agent" now, can this be opened and reviewed again?
