### ISSUE TITLE
Is it possible to setup RockNSM in a VPS, and route another VPS's traffic through it?

### ISSUE THREAD

**Issue by orange888** [rocknsm/rock#527]
Is it possible to setup RockNSM in a VPS (1), and route another VPS's traffic through it (VPS1)?
Any example?
Thanks.

**Comment by spartan782** [comment]
I would think it is possible but don't have any experience there. I would highly recommend you try posting here for think kind of support as there is a larger community on the forums than just those of us using the github issues for bugs and feature requests. 

https://community.rocknsm.io/
