### ISSUE TITLE
2.5 historic PCAP ingest

### ISSUE THREAD

**Issue by somestranger** [rocknsm/rock#534]
when attempting to run
  sudo -u zeek -g zeek /usr/bin/zeek -C -r ${item} local
or 
  sudo -u suricata -g suricata /usr/bin/suricata  -k -r ${item}
there are a number of permission issues.

in 2.4 both of these commands would create the logs in the current directory as well as ship the json straight to kafka, this seems to be partially working. ( except for errors associated with creating the /data/bro/logs/extract_files/ directories which FSF then immediately fails to pull from as they dont exist.
 
[manual suricata run.txt](https://github.com/rocknsm/rock/files/4241297/manual.suricata.run.txt)
[manual zeek run as root.txt](https://github.com/rocknsm/rock/files/4241298/manual.zeek.run.as.root.txt)
[manual zeek run.txt](https://github.com/rocknsm/rock/files/4241299/manual.zeek.run.txt)

please let me know what else i can provide

**Comment by somestranger** [comment]
Update to the suricata run. i can get it to run if i run it with the suricata user and group from /data/suricata however the logs never make it to kafka.

**Comment by peasead** [comment]
@somestranger okay, I think we found & fixed the issue.

The issue appears that Zeek is trying to write to `/data/bro/logs/extracted_files`, but as you may remember, Bro is now Zeek, so it *should* be writing to `/data/zeek/logs/extracted_files`. @dcode has fixed this and a new ISO will be cut.

As a manual workaround, you can just create the Bro directory and give ownership to the `zeek` user and group.

```
sudo mkdir -p /data/bro/logs/extracted_files
sudo chown -R zeek: /data/bro
```

After that, `sudo /usr/bin/zeek -C -r file.pcap local` should work. I have validated that the data is moving through the pipeline and in Kibana.

**Comment by peasead** [comment]
Reopening because of the Suricata issue. Haven't tested this yet.

LMK if that issue persists.

**Comment by peasead** [comment]
@somestranger I just tested this manual fix and we're in business

https://github.com/rocknsm/rock-scripts/compare/b2a547c6fb8a...2dc24f25e7dd

Fresh ISO is here https://download.rocknsm.io/isos/testing/rocknsm-20200225-08:00:33.iso

We'll move this to stable after a burn-in.
