### ISSUE TITLE
fix xkcd 

### ISSUE THREAD

**Issue by koelslaw** [rocknsm/rock#583]
https://github.com/rocknsm/rock/blob/9faf12dbbf6c696dcaeacb433ac4c14ab28cb984/roles/lighttpd/tasks/main.yml#L7

Results in:

`2021-05-16 03:22:57,762 p=11715 u=root n=ansible | fatal: [simplerockbuild.simplerock.lan]: FAILED! => {"changed": false, "msg": "No package matching 'python2-xkcdpass' found available, installed or updated", "rc": 126, "results": ["No package matching 'python2-xkcdpass' found available, installed or updated"]}`

cloned `xkcd` repo as a work-around, installed manually using `sudo python XKCD-password-generator/setup.py install` and commented out the installation. 

Conditions:
- 4 Cores 
- 2 NICs
- 16 GB RAM
- Automated Install
- Single Node
- rocknsm-20210514-14_14_30.iso

**Comment by spartan782** [comment]
Will need to do some more digging here. My Install was able to installed this package. 

Conditions:

- 4 Cores
- 2 NICs
- 16 GB RAM
- Custom Install (only modified partitions, no modifications to the default rock deploy)
- Single Node
- rocknsm-20210514-14_14_30.iso

**Comment by spartan782** [comment]
closing because this is also addressed in issue #597 which has a proposed way forward.
