### ISSUE TITLE
Version 2.6.0-2111 (rocknsm-20211126-08:00:35.iso) Error: [esaggs] > Invalid string. Length must be a multiple of 4

### ISSUE THREAD

**Issue by thetechgy** [rocknsm/rock#591]
I just deployed rocknsm-20211126-08:00:35.iso and ran a `yum update` immediately after the install and the Kibana dashboards show the error '[esaggs] > Invalid string. Length must be a multiple of 4' as shown in the screenshot
![Kibana_Error](https://user-images.githubusercontent.com/17523918/143663370-2e9e4328-35e3-40bd-8fc1-b7c3f22746d1.png)

Here are the package updates that were performed
![PackageUpdates](https://user-images.githubusercontent.com/17523918/143663414-b38f95d9-bc4e-4450-9f00-8900e7f7b255.jpg)

I'm not sure what else to provide that may be helpful but I can provide any log files

All ROCK services appear to be running and restarting them or rebooting the machine appears to have no effect

**Comment by thetechgy** [comment]
Edge console errors 
![image](https://user-images.githubusercontent.com/17523918/143663926-a8d0253b-dc9b-4e2e-904f-18444bc4bd79.png)

**Comment by thetechgy** [comment]
I've also verified via tcpdump that the monitor interface is seeing traffic as it should

**Comment by webhead404** [comment]
Hi @thetechgy! There is an issue with the reverse proxy not knowing how to handle some of the API calls from Kibana. The temporary solution is to disable `lighttpd` and open up the Kibana port `5601` on the firewall while we work on a fix.

**Comment by thetechgy** [comment]
> lighttpd

I disabled the lighttpd and firewalld services to test and can't seem to connect on 5601 despite the fact that the server appears to be listening on that port

![image](https://user-images.githubusercontent.com/17523918/143665794-a1fdb3df-4e36-4d37-8e28-395209d6e4a7.png)

**Comment by webhead404** [comment]
Remember it won't be over TLS anymore since the reverse proxy was doing that for you. Did you try it over http?

**Comment by thetechgy** [comment]
> Remember it won't be over TLS anymore since the reverse proxy was doing that for you. Did you try it over http?

I tried both and neither load - the browser displays ERR_CONNECTION_REFUSED despite running `sudo systemctl stop firewalld`

**Comment by webhead404** [comment]
Are you running this in a VM?

**Comment by thetechgy** [comment]
> Are you running this in a VM?

No, physical machine that was running 2.5.0 a while back. Ran hardware diagnostics and then used the rocknsm-20211126-08:00:35.iso for install

**Comment by thetechgy** [comment]
@webhead404 figured it out - modified /etc/kibana/kibana.yml to add server.host and set the value to the private IP - it was only listening on localhost, probably because of the reverse proxy

**Comment by webhead404** [comment]
That was going to be my next place to look. Glad you figured it out!

**Comment by thetechgy** [comment]
> That was going to be my next place to look. Glad you figured it out!

Thanks for the help - never would've figured it out on my own!
