### ISSUE TITLE
https://download.rocknsm.io is offline/unavailable | no repo for ISO pull

### ISSUE THREAD

**Issue by rezpc** [rocknsm/rock#599]
Attempted to download the ISO, however https://download.rocknsm.io/isos/stable/ appears to have been offline for quite awhile now. Attempted to build the ISO using the rock-createiso repo but it appears the scripts are outdated as I received a multitude of pull errors.

**Comment by spartan782** [comment]
Apologies as this is a known issue. The only EL7 Rocknsm was very broken due to the python2 purge. We are getting very close to have a new EL9 ISO and will update the download and createiso script once all the bugs and errors have been worked though.
