### ISSUE TITLE
Create JSON alternative for snort

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#70]
Create a systemd service that runs idstool to generate JSON events for snort. This then needs to be ingested by logstash as is currently done with suricata eve.json

See https://blog.jasonish.org/2014/04/16/snort-logstash-elastic-search-and-kibana/

**Comment by dcode** [comment]
This isn't gonna happen for 2.0. Fall back to Bro unified2 reader

**Comment by bndabbs** [comment]
Snort is no longer supported in ROCK.
