### ISSUE TITLE
Create Kibana test

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#8]
Need to upgrade Kibana to 4.2 and create bats test for status to be green

See https://www.elastic.co/guide/en/kibana/current/status.html

**Comment by dcode** [comment]
Need to enable kibana log in `/opt/kibana/config/kibana.yml`.

Needs template.

set the following:
```log_file: /var/log/kibana.log```

and 
```
touch /var/log/kibana.log
chown kibana:kibana /var/log/kibana.log
```

**Comment by bndabbs** [comment]
@dcode Can this issue be closed?
