### ISSUE TITLE
Brand installer w/ new images

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock#83]
need the product.img/setup.img for anaconda to swap out pixmaps and provide an overall pretty experience.

**Comment by dcode** [comment]
@peasead will provide the images

**Comment by peasead** [comment]
Done and done.

https://github.com/rocknsm/SimpleRock/commit/10dd0f80bc981a742ee654b549520077ac6aaf91

**Comment by peasead** [comment]
anaconda still needs to be done. Reopening.

**Comment by dcode** [comment]
Completed by @jeffgeiger and I. Jeff was too lazy to make a commit and just shuffled me some files, so I get the credit.
