### ISSUE TITLE
Need to be able to specify Ethernet monitoring interface

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#9]
I need to be able to specify the Ethernet monitoring interface.  Short-term fix is to manually modify the Chef code to specify the specific interface that monitoring needs to take place on, but not sure how to do that.

**Comment by dcode** [comment]
As a temporary work around, you could hard-code one at Line 189 of default.rb:
https://github.com/CyberAnalyticDevTeam/SimpleRock/blob/master/cookbooks/simplerock/recipes/default.rb#L189

So it would look something like:

~~~~~~~~~
node.run_state['monif'] = 'enp8s0'
~~~~~~~~~

**Comment by dcode** [comment]
This is fixed in the new ansible fork. It allows specifying multiple interfaces. Docs to follow
