### ISSUE TITLE
Add lsof

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#90]
Add lsof to base build of CentOS, because lsof

**Comment by dcode** [comment]
I'll add this to the ISO, but it's not a strict dependency of the collection aspects, so I'll exclude this from the ansible scripts.

**Comment by dcode** [comment]
This didn't make it into the official ISO as we want to really keep that minimal. Support for custom packages is possible by creating a custom ISO and adding packages to the file `local.list`. The `offline-snapshot.sh` script will pull in additional pacakges as needed and place them in the ISO repo directory for offline use.
