### ISSUE TITLE
In Kibana, Bro logs common field names are duplicated for each log type

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#91]
In Kibana, Bro logs fields are strangely identified with duplicates for common field names per log type:
@meta.event_type
t@meta.id
t@meta.proc
t@meta.related_ids
t@meta.stream
t@meta.system
t@version
t_index
#_score
tfiles.@version
tfiles.analyzers
tfiles.conn_uids
#files.depth
#files.duration
?files.filename
tfiles.fuid
files.local_orig
tfiles.md5
tfiles.mime_type
#files.missing_bytes
#files.overflow_bytes
#files.seen_bytes
files.timedout
#files.total_bytes
files.ts
tfiles.tx_hosts
tnotice.actions
notice.dropped
tnotice.dst
tnotice.id_orig_h
#notice.id_orig_p
tnotice.id_resp_h
#notice.id_resp_p
tnotice.msg
tnotice.note
#notice.p
tnotice.peer_descr
tnotice.proto
tnotice.src
tnotice.sub
#notice.suppress_for
notice.ts
tnotice.uid
?tags
tweird.@version
tweird.id_orig_h
#weird.id_orig_p
tweird.id_resp_h
#weird.id_resp_p
tweird.name
weird.notice
tweird.peer
weird.ts
tweird.uid
tx509.@version
x509.basic_constraints_ca
#x509.basic_constraints_path_len
tx509.certificate_curve
tx509.certificate_exponent
tx509.certificate_issuer
tx509.certificate_key_alg
#x509.certificate_key_length
tx509.certificate_key_type
x509.certificate_not_valid_after
x509.certificate_not_valid_before
tx509.certificate_serial
tx509.certificate_sig_alg
tx509.certificate_subject
#x509.certificate_version
tx509.fuid
tx509.san_dns
x509.ts

**Comment by dcode** [comment]
I'm not sure why your field names are prefixed with the letter 't', but this is something that needs documentation to understand what was changed and the rationale.

**Comment by akniffe1** [comment]
I think the t prefix is the field data type identifier from kibana. If you copy and paste the field list you'll get "t" for text/string, "#" for int like so:
```
t@meta.event_type
t@meta.geoip_resp.city_name
```

**Comment by bndabbs** [comment]
This is by design. Common fields sit under `@meta` and per-stream fields are sub-fields to the stream name.
